export const properties = [
    {
        id: 1,
        name: "Luxury Seaside Villa",
        propertyType: "Villa",
        location: {
          area: "Candolim",
          city: "North Goa",
          state: "Goa",
          country: "India",
        },
        price: 2500000,
        bedrooms: 5,
        bathrooms: 4,
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRoX0In-r5_WMQgQtkpNsqLYDdTyjH-4RR0rA&usqp=CAU",
      },
      {
        id: 2,
        name: "Spacious Beachfront Apartment",
        propertyType: "Apartment",
        location: {
          area: "Calangute",
          city: "North Goa",
          state: "Goa",
          country: "India",
        },
        price: 800000,
        bedrooms: 2,
        bathrooms: 2,
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRoX0In-r5_WMQgQtkpNsqLYDdTyjH-4RR0rA&usqp=CAU",
      },
      {
        id: 3,
        name: "Beautiful Riverfront House",
        propertyType: "House",
        location: {
          area: "Panaji",
          city: "North Goa",
          state: "Goa",
          country: "India",
        },
        price: 1200000,
        bedrooms: 3,
        bathrooms: 3,
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRoX0In-r5_WMQgQtkpNsqLYDdTyjH-4RR0rA&usqp=CAU",
      },
      {
        id: 4,
        name: "Ocean View Land",
        propertyType: "Land",
        location: {
          area: "Vagator",
          city: "North Goa",
          state: "Goa",
          country: "India",
        },
        price: 500000,
        bedrooms: 0,
        bathrooms: 0,
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRoX0In-r5_WMQgQtkpNsqLYDdTyjH-4RR0rA&usqp=CAU",
      },
      {
        id: 5,
        name: "Modern Office Space",
        propertyType: "Office",
        location: {
          area: "Margao",
          city: "South Goa",
          state: "Goa",
          country: "India",
        },
        price: 1000000,
        bedrooms: 0,
        bathrooms: 0,
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRoX0In-r5_WMQgQtkpNsqLYDdTyjH-4RR0rA&usqp=CAU",
      },
      {
        id: 6,
        name: "Historic Portuguese Mansion",
        propertyType: "Portuguese House",
        location: {
          area: "Assagao",
          city: "North Goa",
          state: "Goa",
          country: "India",
        },
        price: 3000000,
        bedrooms: 7,
        bathrooms: 6,
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRoX0In-r5_WMQgQtkpNsqLYDdTyjH-4RR0rA&usqp=CAU",
      },
      {
        id: 7,
        name: "Luxurious Resort Property",
        propertyType: "Resale Properties",
        location: {
          area: "Cavelossim",
          city: "South Goa",
          state: "Goa",
          country: "India",
        },
        price: 4500000,
        bedrooms: 10,
        bathrooms: 8,
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRoX0In-r5_WMQgQtkpNsqLYDdTyjH-4RR0rA&usqp=CAU",
      },
      {
        id: 8,
        name: "Scenic Hilltop Retreat",
        propertyType: "Villa",
        location: {
          area: "Aldona",
          city: "North Goa",
          state: "Goa",
          country: "India",
        },
        price: 3200000,
        bedrooms: 6,
        bathrooms: 5,
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRoX0In-r5_WMQgQtkpNsqLYDdTyjH-4RR0rA&usqp=CAU",
      },
      {
        id: 9,
        name: "Charming Beach House",
        propertyType: "House",
        location: {
          area: "Morjim",
          city: "North Goa",
          state: "Goa",
          country: "India",
        },
        price: 900000,
        bedrooms: 4,
        bathrooms: 3,
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRoX0In-r5_WMQgQtkpNsqLYDdTyjH-4RR0rA&usqp=CAU",
      },
  ];